name = "public-inventory"
type = "javascript"

account_id = "YOUR ACCOUNT ID"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-05-12"

[[r2_buckets]]
binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'inventory'
